remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Crystal Space
description: Crystal Space App
show_downloads: false
include:
  - .well-known
github:
  is_project_page: false
